"""Added email to User

Revision ID: 1a1eafa91ae2
Revises: 7f6ed00bd089
Create Date: 2023-06-22 17:42:21.386374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1eafa91ae2'
down_revision = '7f6ed00bd089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uix_1', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uix_1', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
